### PR TITLE
Html markdown

### PR DESCRIPTION
**Pull request by mcandre**
Yay, it was pretty easy to add colors for HTML / Markdown headers once I knew the region names from vim-markdown.

### CODE REVIEW

**Comment by benjaminwhite** [comment]
Hi! Thank you for the pull request. I looked over your changes and have a few thoughts:

1. I use markdown all the time for note taking and agree that Benokai is currently lacking in markdown syntax highlighting.

2.

**Comment by mcandre** [comment]
2. ?

**Comment by benjaminwhite** [comment]
> 2 ?

I don't understand.

**Comment by mcandre** [comment]
For a few minutes, the numbered list ended at "2. " with no more content, haha.

Yes, I think that's a good improvement to make on this.

**Comment by mcandre** [comment]
Could we also highlight the sharps (`#`) as part of the header? I really want markdown syntax to do this, but I can't figure out how to make this happen.

**Comment by benjaminwhite** [comment]
I believe that would require changing how syntax regions are specified.

If you're using [vim-markdown](https://github.com/plasticboy/vim-markdown/), you can see how the syntax groups htmlH[1-6] are defined on lines 90-97 of [syntax/mkd.vim](https://github.com/plasticboy/vim-markdown/blob/master/syntax/mkd.vim).

My knowledge of vimscript is a bit too limited to know a solution for your issue. If you want to learn more Vimscript, I would suggest Steve Losh's [Learn Vimscript the Hard Way](http://learnvimscriptthehardway.stevelosh.com/) which has [multiple chapters on syntax highlighting](http://learnvimscriptthehardway.stevelosh.com/chapters/45.html#basic-syntax-highlighting).

**Pull request merged**
